name: CI

on:
  pull_request:
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.APT_REPO_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.APT_REPO_AWS_SECRET_ACCESS_KEY }}
  AWS_BUCKET_NAME: stol-apt-repository

jobs:
  git-revision-info-get:
    uses: usdot-fhwa-stol/actions/.github/workflows/git-revision-info.yml@main
  build-package:
    runs-on: ubuntu-latest
    needs: git-revision-info-get
    container:
      image: ghcr.io/usdot-fhwa-stol/carma-builds:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update
          ./install_dependencies.sh
      - name: Get SAE ASN
        uses: actions/checkout@v3
        with:
          repository: usdot-fhwa-stol/CARMASensitive
          ref: sae_asn
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: CARMASensitive
      - name: Copy SAE ASN
        run: |
          mkdir -p asn/sae
          cp "CARMASensitive/asn/J2735_201603DA_copyright_updated 12.2.ASN" asn/sae/J2735_201603DA.asn
      - name: Install ASN1C
        run: |
          ./install_asn1c.sh
      - name: Generate C and H files
        run: |
          ./generate.sh
      - name: Build
        uses: usdot-fhwa-stol/actions/build-cpp-library@main
        with:
          package-version-suffix: ${{ needs.git-revision-info-get.outputs.git-revision-info }}
      - name: Setup deb-s3
        uses: usdot-fhwa-stol/actions/setup-deb-s3@main
      - name: Upload .deb files
        run: |
          deb-s3 upload --codename develop --bucket ${{ env.AWS_BUCKET_NAME }} build/_packages/*.deb
